name: Build main and release images
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

# Tags should not save the cache as they wont be ever reused for further builds
# so we only set the cache save on branch builds
concurrency:
  group: ci-image-${{ github.ref_name }}-${{ github.repository }}
  cancel-in-progress: ${{ github.ref_name == 'main' }} # Only cancel in-progress for branch builds, never for tags
jobs:
  toolchain-amd64:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}-toolchain:${{ github.ref_name }}-amd64
          labels: ${{ steps.meta.outputs.labels }}
          target: toolchain
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
          cache-to: ${{ github.ref_name == 'main' && 'type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max,ignore-error=true,compression=zstd,compression-level=3,oci-mediatypes=true,image-manifest=true' || 'type=inline,ignore-error=true' }}
  toolchain-arm64:
    runs-on: oracle-vm-32cpu-128gb-arm64
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-toolchain:${{ github.ref_name }}-arm64
          labels: ${{ steps.meta.outputs.labels }}
          target: toolchain
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64,mode=max
          cache-to: ${{ github.ref_name == 'main' && 'type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3,oci-mediatypes=true,image-manifest=true' || 'type=inline,ignore-error=true' }}
          build-args: |
            ARCH=aarch64
            BUILD_ARCH=aarch64
  toolchain:
    needs:
      - toolchain-amd64
      - toolchain-arm64
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}-toolchain
      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            ghcr.io/${{ github.repository }}-toolchain:${{ github.ref_name }}-amd64
            ghcr.io/${{ github.repository }}-toolchain:${{ github.ref_name }}-arm64
      - uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          container: "${{ github.event.repository.name }}-toolchain"
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: 'false'
          keep-tags-regexes: |
            ^main$
            ^v\d+\.\d+\.\d+(-(beta|alpha|rc)[\.-]?\d*)?$
          prune-tags-regexes: |
            ^${{ github.ref_name }}-amd64$
            ^${{ github.ref_name }}-arm64$
  container-amd64:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - toolchain
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@3227f5311cb93ffd14d13e65d8cc400d30f4dd8a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}-container:${{ github.ref_name }}-amd64
          labels: ${{ steps.meta.outputs.labels }}
          target: container
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64,mode=max
          cache-to: ${{ github.ref_name == 'main' && 'type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64,mode=max,ignore-error=true,compression=zstd,compression-level=3,oci-mediatypes=true,image-manifest=true' || 'type=inline,ignore-error=true' }}
  container-arm64:
    runs-on: oracle-vm-32cpu-128gb-arm64
    needs:
      - toolchain
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@3227f5311cb93ffd14d13e65d8cc400d30f4dd8a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-container:${{ github.ref_name }}-arm64
          labels: ${{ steps.meta.outputs.labels }}
          target: container
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64,mode=max
          cache-to: ${{ github.ref_name == 'main' && 'type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3,oci-mediatypes=true,image-manifest=true' || 'type=inline,ignore-error=true' }}
          build-args: |
            ARCH=aarch64
            BUILD_ARCH=aarch64
  container:
    needs:
      - container-amd64
      - container-arm64
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}-container
      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            ghcr.io/${{ github.repository }}-container:${{ github.ref_name }}-amd64
            ghcr.io/${{ github.repository }}-container:${{ github.ref_name }}-arm64
      - uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          container: "${{ github.event.repository.name }}-container"
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: 'false'
          keep-tags-regexes: |
            ^main$
            ^v\d+\.\d+\.\d+(-(beta|alpha|rc)[\.-]?\d*)?$
          prune-tags-regexes: |
            ^${{ github.ref_name }}-amd64$
            ^${{ github.ref_name }}-arm64$
  hadron-bios-amd64:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: [ "cloud", "default" ]
        fips: [ "no-fips" ]
        include:
          - kernel: "cloud"
            fips: "fips"
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}${{ matrix.fips == 'fips' && '-fips' || '' }}:${{ github.ref_name }}-amd64
          labels: ${{ steps.meta.outputs.labels }}
          target: default
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:bios-${{ matrix.kernel }}-${{ matrix.fips }}-amd64,mode=max
          cache-to: ${{ github.ref_name == 'main' && format('type=registry,ref=quay.io/kairos/hadron-build-cache:bios-{0}-{1}-amd64,mode=max,ignore-error=true,compression=zstd,compression-level=3,oci-mediatypes=true,image-manifest=true', matrix.kernel, matrix.fips) || 'type=inline,ignore-error=true' }}
          build-args: |
            BOOTLOADER=grub
            KERNEL_TYPE=${{ matrix.kernel }}
            FIPS=${{ matrix.fips }}
  hadron-bios-arm64:
    runs-on: oracle-vm-32cpu-128gb-arm64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: [ "cloud", "default" ]
        fips: [ "no-fips" ]
        include:
          - kernel: "cloud"
            fips: "fips"
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}${{ matrix.fips == 'fips' && '-fips' || '' }}:${{ github.ref_name }}-arm64
          labels: ${{ steps.meta.outputs.labels }}
          target: default
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:bios-${{ matrix.kernel }}-${{ matrix.fips }}-arm64,mode=max
          cache-to: ${{ github.ref_name == 'main' && format('type=registry,ref=quay.io/kairos/hadron-build-cache:bios-{0}-{1}-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3,oci-mediatypes=true,image-manifest=true', matrix.kernel, matrix.fips) || 'type=inline,ignore-error=true' }}
          build-args: |
            BOOTLOADER=grub
            KERNEL_TYPE=${{ matrix.kernel }}
            FIPS=${{ matrix.fips }}
            ARCH=aarch64
            BUILD_ARCH=aarch64
  hadron-bios:
    needs:
      - hadron-bios-amd64
      - hadron-bios-arm64
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        kernel: [ "cloud", "default" ]
        fips: [ "no-fips" ]
        include:
          - kernel: "cloud"
            fips: "fips"
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}${{ matrix.fips == 'fips' && '-fips' || '' }}
      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}${{ matrix.fips == 'fips' && '-fips' || '' }}:${{ github.ref_name }}-amd64
            ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}${{ matrix.fips == 'fips' && '-fips' || '' }}:${{ github.ref_name }}-arm64
      - uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          container: "${{ github.event.repository.name }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}${{ matrix.fips == 'fips' && '-fips' || '' }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: 'false'
          keep-tags-regexes: |
            ^main$
            ^v\d+\.\d+\.\d+(-(beta|alpha|rc)[\.-]?\d*)?$
          prune-tags-regexes: |
            ^${{ github.ref_name }}-amd64$
            ^${{ github.ref_name }}-arm64$
  hadron-trusted-amd64:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: [ "cloud", "default" ]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted:${{ github.ref_name }}-amd64
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:trusted-${{ matrix.kernel }}-amd64,mode=max
          cache-to: ${{ github.ref_name == 'main' && format('type=registry,ref=quay.io/kairos/hadron-build-cache:trusted-{0}-amd64,mode=max,ignore-error=true,compression=zstd,compression-level=3,oci-mediatypes=true,image-manifest=true', matrix.kernel) || 'type=inline,ignore-error=true' }}
          target: default
          build-args: |
            BOOTLOADER=systemd
            KERNEL_TYPE=${{ matrix.kernel }}
  hadron-trusted-arm64:
    runs-on: oracle-vm-32cpu-128gb-arm64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: [ "cloud", "default" ]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted:${{ github.ref_name }}-arm64
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:trusted-${{ matrix.kernel }}-arm64,mode=max
          cache-to: ${{ github.ref_name == 'main' && format('type=registry,ref=quay.io/kairos/hadron-build-cache:trusted-{0}-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3,oci-mediatypes=true,image-manifest=true', matrix.kernel) || 'type=inline,ignore-error=true' }}
          target: default
          build-args: |
            BOOTLOADER=systemd
            KERNEL_TYPE=${{ matrix.kernel }}
            ARCH=aarch64
            BUILD_ARCH=aarch64
  hadron-trusted:
    needs:
      - hadron-trusted-amd64
      - hadron-trusted-arm64
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        kernel: [ "cloud", "default" ]
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted
      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted:${{ github.ref_name }}-amd64
            ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted:${{ github.ref_name }}-arm64
      - uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          container: "${{ github.event.repository.name }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted"
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: 'false'
          keep-tags-regexes: |
            ^main$
            ^v\d+\.\d+\.\d+(-(beta|alpha|rc)[\.-]?\d*)?$
          prune-tags-regexes: |
            ^${{ github.ref_name }}-amd64$
            ^${{ github.ref_name }}-arm64$