name: Build examples

on:
  workflow_dispatch:
  push:
    paths:
      - '../../examples/add-packages/**'

jobs:
  build:
    name: ${{ matrix.extra-file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extra-file:
          - "Dockerfile.git"
          - "Dockerfile.gpg"
          - "Dockerfile.fwupd"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Dockerfile
        uses: docker/build-push-action@v6
        with:
          file: examples/add-packages/${{ matrix.extra-file }}
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64
            type=registry,ref=quay.io/kairos/hadron-build-cache:bios-cloud-amd64
            type=registry,ref=quay.io/kairos/hadron-build-cache:bios-default-amd64
            type=registry,ref=quay.io/kairos/hadron-build-cache:trusted-cloud-amd64
            type=registry,ref=quay.io/kairos/hadron-build-cache:trusted-default-amd64