---
name: 'PR build and test images (amd64)'

on:
  pull_request:

concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  toolchain:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
      - name: Build PR
        uses: docker/build-push-action@v7
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ttl.sh/hadron-toolchain:${{ github.sha }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            cache-label=quay-remote-amd64
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
          target: toolchain
  container:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - toolchain
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
      - name: Build PR
        uses: docker/build-push-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ttl.sh/hadron-container:${{ github.sha }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            cache-label=quay-remote-amd64
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64,mode=max
          target: container
      - name: Test container image
        uses: docker/build-push-action@v7
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          target: container-test
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64,mode=max
  hadron-bios:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: ["cloud", "default"]
        fips: [ "no-fips" ]
        include:
          - kernel: "cloud"
            fips: "fips"
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
      - name: Build PR
        uses: docker/build-push-action@v7
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ttl.sh/hadron${{ matrix.kernel == 'cloud' && '-cloud' || '' }}${{ matrix.fips == 'fips' && '-fips' || '' }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          target: default
          cache-from:
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:bios-${{ matrix.kernel }}-${{ matrix.fips }}-amd64,mode=max
          build-args: |
            BOOTLOADER=grub
            KERNEL_TYPE=${{ matrix.kernel }}
            FIPS=${{ matrix.fips }}
  hadron-trusted:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: [ "cloud", "default" ]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
      - name: Build PR
        uses: docker/build-push-action@v7
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ttl.sh/hadron${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          target: default
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-amd64,mode=max
            type=registry,ref=quay.io/kairos/hadron-build-cache:trusted-${{ matrix.kernel }}-amd64,mode=max
          build-args: |
            BOOTLOADER=systemd
            KERNEL_TYPE=${{ matrix.kernel }}
  build-kairos-bios:
    runs-on: ubuntu-latest
    needs:
      - hadron-bios
    strategy:
      matrix:
        fips: [ "no-fips", "fips" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Download Dockerfile from kairos repository
        run: |
          mkdir -p build
          curl -sSL https://raw.githubusercontent.com/kairos-io/kairos/master/images/Dockerfile -o build/Dockerfile.kairos
      - name: Build and push
        uses: docker/build-push-action@v7
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./build/Dockerfile.kairos
          push: true
          tags: ttl.sh/hadron-init-bios${{ matrix.fips == 'fips' && '-fips' || '' }}:${{ github.sha }}
          build-args: |
            BASE_IMAGE=ttl.sh/hadron-cloud${{ matrix.fips == 'fips' && '-fips' || '' }}:${{ github.sha }}
            VERSION=v0.0.1-${{ github.sha }}
            TRUSTED_BOOT=false
            FIPS=${{ matrix.fips }}
  build-kairos-trusted:
    runs-on: ubuntu-latest
    needs:
      - hadron-trusted
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Download Dockerfile from kairos repository
        run: |
          mkdir -p build
          curl -sSL https://raw.githubusercontent.com/kairos-io/kairos/master/images/Dockerfile -o build/Dockerfile.kairos
      - name: Build and push
        uses: docker/build-push-action@v7
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./build/Dockerfile.kairos
          push: true
          tags: ttl.sh/hadron-init-trusted:${{ github.sha }}
          build-args: |
            BASE_IMAGE=ttl.sh/hadron-cloud-trusted:${{ github.sha }}
            VERSION=v0.0.1-${{ github.sha }}
            TRUSTED_BOOT=true
  build-bios-iso:
    runs-on: ubuntu-latest
    needs:
      - build-kairos-bios
    strategy:
      matrix:
        fips: [ "no-fips", "fips" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build ISO
        run: |
          mkdir build
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD/build/:/output \
          quay.io/kairos/auroraboot:v0.19.2 --debug build-iso --output /output/ \
          --override-name kairos-hadron-bios${{ matrix.fips == 'fips' && '-fips' || '' }}-${{ github.sha }} \
          docker:ttl.sh/hadron-init-bios${{ matrix.fips == 'fips' && '-fips' || '' }}:${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: kairos-hadron-bios${{ matrix.fips == 'fips' && '-fips' || '' }}-${{ github.sha }}.iso.zip
          path: build/*.iso
  build-trusted-iso:
    runs-on: ubuntu-latest
    needs:
      - build-kairos-trusted
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build ISO
        run: | # when agent has fixed the bootentry selection, we can add --sdboot-in-source to use the bundled sdboot
          mkdir build
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD/tests/assets/keys:/keys \
          -v $PWD/build/:/output \
          -v $PWD/tests/assets/sysext/:/overlay \
          quay.io/kairos/auroraboot:v0.19.2 --debug build-uki \
          --output-dir /output/ --public-keys /keys \
          --tpm-pcr-private-key /keys/tpm2-pcr-private.pem \
          --sb-key /keys/db.key \
          --sb-cert /keys/db.pem \
          --output-type iso \
          --overlay-iso /overlay \
          docker:ttl.sh/hadron-init-trusted:${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: kairos-hadron-trusted-${{ github.sha }}.iso.zip
          path: build/*.iso
  tests-bios:
    runs-on: fast # Custom runner, more memory and CPU
    name: ${{ matrix.test }} tests
    needs:
      - build-bios-iso
    strategy:
      matrix:
        test:
          - "acceptance"
          - "reset"
          - "custom-partitioning"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        timeout-minutes: 5
        with:
          go-version-file: tests/go.mod
          cache-dependency-path: tests/go.sum
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: kairos-hadron-bios-${{ github.sha }}.iso.zip
      - name: Enable KVM group perms
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu-system qemu-system-x86 qemu-system-x86 qemu-utils qemu-kvm acl udev mkisofs swtpm
          sudo setfacl -m u:runner:rwx /dev/kvm
      - name: Run tests
        env:
          USE_QEMU: true
          KVM: true
          MEMORY: 5000
          DRIVE_SIZE: 50000
          CREATE_VM: true
          CPUS: 4
        run: |
          export ISO=$PWD/$(ls *.iso|grep -v ipxe | head -1 )
          echo "ISO is: $ISO"
          cp tests/go.* .
          go mod download
          go run github.com/onsi/ginkgo/v2/ginkgo -v --fail-fast -r --label-filter "${{ matrix.test }}" ./tests/
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        if: failure()
        with:
          name: acceptance-${{github.sha}}.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
  tests-trusted:
    runs-on: fast # Custom runner, more memory and CPU
    name: ${{ matrix.test }} tests
    needs:
      - build-trusted-iso
    strategy:
      matrix:
        test:
          - "acceptance-trusted-generic"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        timeout-minutes: 5
        with:
          go-version-file: tests/go.mod
          cache-dependency-path: tests/go.sum
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: kairos-hadron-trusted-${{ github.sha }}.iso.zip
      - name: Enable KVM group perms
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu-system qemu-system-x86 qemu-system-x86 qemu-utils qemu-kvm acl udev mkisofs swtpm
          sudo setfacl -m u:runner:rwx /dev/kvm
      - name: Run tests
        env:
          USE_QEMU: true
          KVM: true
          MEMORY: 5000
          DRIVE_SIZE: 50000
          CREATE_VM: true
          CPUS: 4
          FIRMWARE: /usr/share/OVMF/OVMF_CODE_4M.secboot.fd
          EMULATE_TPM: true
          UKI_TEST: true
        run: |
          export ISO=$PWD/$(ls *.iso|grep -v ipxe | head -1 )
          echo "ISO is: $ISO"
          cp tests/go.* .
          go mod download
          go run github.com/onsi/ginkgo/v2/ginkgo -v --fail-fast -r --label-filter "${{ matrix.test }}" ./tests/
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        if: failure()
        with:
          name: acceptance-trusted-${{github.sha}}.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
  tests-bios-fips:
    runs-on: fast # Custom runner, more memory and CPU
    name: ${{ matrix.test }} tests (FIPS)
    needs:
      - build-bios-iso
    strategy:
      matrix:
        test:
          - "acceptance"
          - "reset"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        timeout-minutes: 5
        with:
          go-version-file: tests/go.mod
          cache-dependency-path: tests/go.sum
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: kairos-hadron-bios-fips-${{ github.sha }}.iso.zip
      - name: Enable KVM group perms
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu-system qemu-system-x86 qemu-system-x86 qemu-utils qemu-kvm acl udev mkisofs swtpm
          sudo setfacl -m u:runner:rwx /dev/kvm
      - name: Run tests
        env:
          USE_QEMU: true
          KVM: true
          MEMORY: 5000
          DRIVE_SIZE: 50000
          CREATE_VM: true
          CPUS: 4
          FIPS: true
        run: |
          export ISO=$PWD/$(ls *.iso|grep -v ipxe | head -1 )
          echo "ISO is: $ISO"
          cp tests/go.* .
          go mod download
          go run github.com/onsi/ginkgo/v2/ginkgo -v --fail-fast -r --label-filter "${{ matrix.test }}" ./tests/
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        if: failure()
        with:
          name: ${{ matrix.test }}-${{github.sha}}.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn

